#!/bin/bash
shopt -s dotglob

printf "\n### Cleaning Up ###"

if [ "$(/bin/ls -Aq applications_user)" ]; then
  printf "\nCleaning ./applications_user"
  sleep 2
  rm -rv applications_user/*
fi

if [ "$(/bin/ls -Aq assets/resources/apps)" ]; then
  printf "\nCleaning ./assets/resources/apps"
  sleep 2
  rm -rv assets/resources/apps/*
fi

printf "\nRunning fbt -c\n"
sleep 1
./fbt -c
