#!/bin/bash

shopt -s dotglob

printf "\n### Cleaning Up ###"

if [ "$(/bin/ls -Aq applications_user)" ]; then
  printf "\nCleaning ./applications_user"
  sleep 2
  rm -rv applications_user/*
fi

if [ "$(/bin/ls -Aq assets/resources/apps)" ]; then
  printf "\nCleaning ./assets/resources/apps"
  sleep 2
  rm -rv assets/resources/apps/*
fi

printf "\nRunning fbt -c\n"
sleep 1
./fbt -c

printf "\n### Building Apps ###\n"
sleep 1
./fbt COMPACT=1 DEBUG=0 fap_dist
rsync -r dist/f7-C/apps/ applications_user
printf "\n### Building Firmware Package ###\n"
sleep 1
./fbt COMPACT=1 DEBUG=0 updater_package
